#!/bin/bash
#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=100g
#SBATCH --time=4:00:00
#SBATCH --job-name=bowtie-to-sam
#SBATCH --output=/gpfs01/share/BioinfMSc/life4136_2526/rotation2/group4/Scripts/Logs/slurm-%x-%j.out
#SBATCH --error=/gpfs01/share/BioinfMSc/life4136_2526/rotation2/group4/Scripts/Logs/slurm-%x-%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mbxas28@nottingham.ac.uk

#Activates the conda environment
source $HOME/.bash_profile
conda activate rotation2

#Setting paths for the files
INPUT_DIR="/share/BioinfMSc/life4136_2526/rotation2/group4/trim-galore/blood_33"
OUTPUT_DIR="/share/BioinfMSc/life4136_2526/rotation2/group4/mapping_bowtie2/sam_files"
INDEX="/share/BioinfMSc/life4136_2526/rotation2/group4/reference_files/index/index"

mkdir -p "$OUTPUT_DIR"

#Creating a for loop so every file is run individually
for FILE in $INPUT_DIR/*.fq.gz
do
  	BASENAME=$(basename "$FILE" .fq.gz)

        echo "Processing $BASENAME"

        bowtie2 \
        -x "$INDEX" \
        -U "$FILE" \
        -p 8 \
	| gzip > "$OUTPUT_DIR/${BASENAME}.sam.gz"

done

conda deactivate

