#!/bin/bash
#SBATCH --partition=defq
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=50g
#SBATCH --time=12:00:00
#SBATCH --job-name=sam_to_bam_blood
#SBATCH --output=/gpfs01/share/BioinfMSc/life4136_2526/rotation2/group4/Scripts/Logs/slurm-%x-%j.out
#SBATCH --error=/gpfs01/share/BioinfMSc/life4136_2526/rotation2/group4/Scripts/Logs/slurm-%x-%j.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=mbxas28@nottingham.ac.uk

#Activates the conda environment
source $HOME/.bash_profile
conda activate rotation2

#Setting file paths
INPUT_DIR="/share/BioinfMSc/life4136_2526/rotation2/group4/mapping_bowtie2/sam_files"
OUTPUT_DIR="/share/BioinfMSc/life4136_2526/rotation2/group4/mapping_bowtie2/bam_files/blood-bam"
OUTPUT_DIR2="/share/BioinfMSc/life4136_2526/rotation2/group4/mapping_bowtie2/bam_files/blood-bam/sorted_blood"

mkdir -p "$OUTPUT_DIR"

#Converting sam files to bam files
for FILE in "$INPUT_DIR"/*.sam.gz
do
    BASENAME=$(basename "$FILE" .sam.gz)
    samtools view -@ 8 -b "$FILE" > "$OUTPUT_DIR/${BASENAME}.bam"

done


for BAM in "$OUTPUT_DIR"/*_trimmed.bam
do
    BASENAME=$(basename "$BAM" .bam)

    samtools sort -@ 8 "$BAM" -o "$OUTPUT_DIR2/${BASENAME}.sorted.bam"
    samtools index "$OUTPUT_DIR2/${BASENAME}.sorted.bam"

done


conda deactivate



